version: '3.7'
services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - server
  server:
    image: server 
    container_name: server
    build: ./server
