apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
  labels: 
    app: basic-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
      - name: basic-app
        image: kubes-jenkins:5000/basic-app:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: basic-app
spec:
  selector:
    app: basic-app
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer