- hosts: localhost
  connection: local
  tasks:
  - name: "Generate key pair"
    openssh_keypair:
      path: ~/.ssh/ansible_id_rsa
      state: present
  - name: "Create key pair using key_material obtained using 'file' lookup plugin"
    ec2_key:
      name: MSP2KeyPair
      key_material: "{{ lookup('file', '~/.ssh/ansible_id_rsa.pub') }}"
      state: present
  - name: "Create a stack"
    cloudformation:
      state: present
      stack_name: MSP2-stack
      region: eu-west-2
      template: stack.yaml
  - cloudformation_info:
      stack_name: MSP2-stack
      stack_resources: true
    register: output
  - ec2_asg_info:
      name: MSP2-ASG
    register: asg
  - ec2_instance_info:
      instance_ids: "{{ asg['results'][0] | json_query('instances[*].instance_id') }}"
    register: ec2
  - debug:
      msg: "{{ ec2 | json_query('instances[*].public_dns_name') | list }}"
  - set_fact:
      ec2_instances: "{{ ec2 | json_query('instances[*].public_dns_name') | list }}"
  - debug:
      msg: "{{ ec2_instances }}"
  - name: "Build inventory"
    add_host:
      name: "{{ item }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ansible_id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectTimeout=60'
    with_items: "{{ ec2_instances }}"

- hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: "Wait for system to become reachable"
    wait_for_connection:
  - name: "Gather facts for first time"
    setup:
  - name: "Install Docker"
    pip:
      name:
      - docker
      - docker_compose
  - name: "Install Dependencies"
    apt:
      name:
      - git
      - python-pip
      - python3-pip
      - docker-ce
      - docker-ce-cli
      state: latest
      update_cache: true
  - name: "Install docker-compose"
    get_url:
      url: https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
  - name: "Make docker-compose executable"
    file:
      path: /usr/local/bin/docker-compose
      mode: +x
  - name: "Add ubuntu user in docker group"
    user:
      name: ubuntu
      shell: /bin/bash
      group: docker
      state: present
  - name: "Pull flask app from git"
    git:
      repo: "https://github.com/htr-volker/basic-app"
      dest: "/opt/basic-app"
      force: yes
  - name: "Run app in Docker"
    docker_compose:
      project_src: /opt/basic-app