- hosts: localhost
  connection: local
  tasks:
  - name: "delete aws key pair"
    ec2_key:
      name: MSP2KeyPair
      state: absent
  - name: "delete key pair"
    openssh_keypair:
      path: ~/.ssh/ansible_id_rsa
      state: absent
  - name: "delete stack"
    cloudformation:
      state: absent
      stack_name: MSP2-stack
      region: eu-west-2